import { Metadata } from "next";
import Link from "next/link";
import ManageCookiesSection from "./cookie-section";

/**
 * ################################################################################
 * ################################### METADATA ###################################
 * ################################################################################
 */
export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "This Privacy Policy outlines how ISATech Society collects, uses, and protects your information.",
  keywords: [
    "philippines",
    "privacy policy",
    "iloilo",
    "ISATU",
    "startups",
    "technopreneurship",
    "ISATech Society",
    "student founders",
    "innovation",
    "collaboration",
    "community",
  ],
  openGraph: {
    title: "Privacy Policy",
    description:
      "This Privacy Policy outlines how ISATech Society collects, uses, and protects your information.",
    url: "https://isatech.club/privacy",
    siteName: "ISATech Society",
    images: [
      {
        url: "/assets/seo/ogimage-privacy.jpg",
        width: 1200,
        height: 630,
        alt: "ISATech Society Privacy Header Image",
      },
    ],
    type: "website",
  },
};

/**
 * ################################################################################
 * ################################## COMPONENTS ##################################
 * ################################################################################
 */

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-4">
      <h2>{title}</h2>
      {children}
    </div>
  );
}

function PrivacyPageHeader() {
  return (
    <div className="flex flex-col gap-2">
      <h1 className="text-primary">Privacy Policy</h1>
      <p className="text-muted-foreground">Last updated: July 29, 2025</p>
    </div>
  );
}

function PrivacyIntroSection() {
  return (
    <div className="flex flex-col gap-4">
      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>
    </div>
  );
}

function PrivacyInterpretationSection() {
  return (
    <Section title="Interpretation and Definitions">
      <h3>Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul className="ml-6 list-disc space-y-2">
        <li>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Company</strong> (referred to as either &quot;the
          Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
          this Agreement) refers to ISATech Society.
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li>
          <strong>Country</strong> refers to: Philippines
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website</strong> refers to ISATech Society, accessible from
          isatech.club
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>
    </Section>
  );
}

function PrivacyDataCollectionSection() {
  return (
    <Section title="Collecting and Using Your Personal Data">
      <h3>Types of Data Collected</h3>
      <h4>Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className="ml-6 list-disc space-y-2">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>
      <h4>Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        Usage Data may include information such as Your Device&apos;s Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <h4>Tracking Technologies and Cookies</h4>
      <p>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. For more information about
        the cookies we use and your choices regarding cookies, please visit our
        Cookies Policy or the Cookies section of our Privacy Policy.
      </p>
    </Section>
  );
}

function PrivacyDataUseSection() {
  return (
    <Section title="Use of Your Personal Data">
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul className="ml-6 list-disc space-y-2">
        <li>
          <strong>To provide and maintain our Service</strong>, including to
          monitor the usage of our Service.
        </li>
        <li>
          <strong>To manage Your Account:</strong> to manage Your registration
          as a user of the Service.
        </li>
        <li>
          <strong>For the performance of a contract:</strong> the development,
          compliance and undertaking of the purchase contract for the products,
          items or services You have purchased.
        </li>
        <li>
          <strong>To contact You:</strong> To contact You by email, telephone
          calls, SMS, or other equivalent forms of electronic communication.
        </li>
        <li>
          <strong>To provide You</strong> with news, special offers and general
          information about other goods, services and events.
        </li>
        <li>
          <strong>To manage Your requests:</strong> To attend and manage Your
          requests to Us.
        </li>
        <li>
          <strong>For business transfers:</strong> We may use Your information
          to evaluate or conduct a merger, divestiture, or other sale or
          transfer of some or all of Our assets.
        </li>
        <li>
          <strong>For other purposes:</strong> We may use Your information for
          other purposes, such as data analysis, identifying usage trends, and
          to evaluate and improve our Service, products, and marketing.
        </li>
      </ul>
    </Section>
  );
}

function PrivacyDataRetentionSection() {
  return (
    <Section title="Retention of Your Personal Data">
      <p>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations, resolve disputes, and enforce our legal
        agreements and policies.
      </p>
    </Section>
  );
}

function PrivacyDataTransferSection() {
  return (
    <Section title="Transfer of Your Personal Data">
      <p>
        Your information, including Personal Data, is processed at the
        Company&apos;s operating offices and in any other places where the
        parties involved in the processing are located. Your consent to this
        Privacy Policy followed by Your submission of such information
        represents Your agreement to that transfer.
      </p>
    </Section>
  );
}

function PrivacyDataDeletionSection() {
  return (
    <Section title="Delete Your Personal Data">
      <p>
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You. You may update, amend,
        or delete Your information at any time by signing in to Your Account, if
        you have one, and visiting the account settings section. You may also
        contact Us to request access to, correct, or delete any personal
        information that You have provided to Us.
      </p>
    </Section>
  );
}

function PrivacyDataDisclosureSection() {
  return (
    <Section title="Disclosure of Your Personal Data">
      <h3>Business Transactions</h3>
      <p>
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred and becomes subject to a different Privacy
        Policy.
      </p>
      <h3>Law enforcement</h3>
      <p>
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </p>
    </Section>
  );
}

function PrivacySecuritySection() {
  return (
    <Section title="Security of Your Personal Data">
      <p>
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </p>
    </Section>
  );
}

function PrivacyChildrenSection() {
  return (
    <Section title="Children's Privacy">
      <p>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us.
      </p>
    </Section>
  );
}

function PrivacyLinksSection() {
  return (
    <Section title="Links to Other Websites">
      <p>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party&apos;s site. We strongly advise You to review the Privacy
        Policy of every site You visit.
      </p>
    </Section>
  );
}

function PrivacyChangesSection() {
  return (
    <Section title="Changes to this Privacy Policy">
      <p>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page. You are
        advised to review this Privacy Policy periodically for any changes.
      </p>
    </Section>
  );
}

function PrivacyContactSection() {
  return (
    <Section title="Contact Us">
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="ml-6 list-disc space-y-2">
        <li>
          By email:{" "}
          <a
            href="mailto:isatech@isatu.edu.ph"
            className="text-primary underline"
          >
            isatech@isatu.edu.ph
          </a>
        </li>
        <li>
          By visiting our{" "}
          <Link href="/contact#" className="text-primary underline">
            contact page
          </Link>
        </li>
      </ul>
    </Section>
  );
}

/**
 * ################################################################################
 * ##################################### PAGE #####################################
 * ################################################################################
 */
export default function PrivacyPage() {
  return (
    <main className="flex w-full flex-col items-center justify-center">
      <section className="w-full px-6 py-16 lg:px-16 lg:py-28">
        <div className="mx-auto flex max-w-4xl flex-col gap-8">
          <PrivacyPageHeader />
          <PrivacyIntroSection />
          <PrivacyInterpretationSection />
          <PrivacyDataCollectionSection />
          <PrivacyDataUseSection />
          <PrivacyDataRetentionSection />
          <PrivacyDataTransferSection />
          <PrivacyDataDeletionSection />
          <PrivacyDataDisclosureSection />
          <PrivacySecuritySection />
          <PrivacyChildrenSection />
          <PrivacyLinksSection />
          <PrivacyChangesSection />
          <PrivacyContactSection />
          <ManageCookiesSection />
        </div>
      </section>
    </main>
  );
}
